### ISSUE TITLE
SV profile- up cast

### ISSUE THREAD

**Issue by CorinneBassin-SOI** [schmidtocean/sealog-client-vehicle#2]
For Discussion:
Adding the upcast SV profile to sealog so that it can be used when transitioning into mapping.

**Comment by CorinneBassin-SOI** [comment]
consider as a script in a jupyter notebook to be run

**Comment by webbpinner** [comment]
just providing comment...
Is this a request to add a button in Sealog for the SV upcast or is this something you'd like done outside of the sealog UI (which is totally possible)?

**Comment by KaarelRaeis-SOI** [comment]
I think this falls outside the scope of sealog as an event logging tool. We'll implement it as a misc script elsewhere.
